# Generated by Django 3.0.7 on 2020-09-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200918_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='note',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
