# Generated by Django 3.0.7 on 2020-10-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201002_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(blank=True, to='store.Product'),
        ),
        migrations.DeleteModel(
            name='Product_tag',
        ),
    ]
