# Generated by Django 3.0.7 on 2020-09-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='user',
        ),
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.CharField(default=3, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
