# Generated by Django 3.0.7 on 2020-09-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20200928_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='set_password',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
