# Generated by Django 3.0.7 on 2020-09-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_seller_set_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='set_password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
