# Generated by Django 3.0.7 on 2020-09-27 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '0004_auto_20200928_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='contact_no',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='set_password',
        ),
        migrations.AddField(
            model_name='seller',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='office_address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
