# Generated by Django 3.0.7 on 2020-09-27 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20200928_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='user',
        ),
    ]
